### ISSUE TITLE
Bad config encountered during initialization: The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f1437bfab80> instance must be a type, but 'dockerspawner.DockerSpawner' could not be imported

### ISSUE THREAD

**Issue by BitPeaches** [jupyterhub/jupyterhub-deploy-docker#109]
Please help, I want to deploy JupyterHub in Docker, and I get an error when starting: Bad config encountered during initialization: `The'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f1437bfab80> instance must be a type, but'dockerspawner.DockerSpawner' could not be imported`
My docker-compose.yaml file:
```
version: '3.1'
services:
  jupyterhub:
    container_name: jupyterhub
    restart: always
    image: jupyterhub/jupyterhub
    ports:
      - 7003:8000
      - 8081:8081
    volumes:
      - /usr/local/docker/jupyterhub/data:/srv/jupyterhub
      - /usr/local/docker/jupyterhub/home:/home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_NETWORK_NAME=jupyterhub_default
      - HUB_IP=jupyterhub

```
我的jupyterhub_config.py文件：
```
import os
c.JupyterHub.bind_url = 'http://0.0.0.0:8000'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.image = 'jupyter/tensorflow-notebook'
c.DockerSpawner.volumes = {'/usr/local/docker/jupyterhub/home/{username}/': '/home/jovyan/work', '/usr/local/docker/jupyterhub/data/config': '/etc/jupyter'}
c.JupyterHub.hub_bind_url = 'http://jupyterhub:8081'
c.Spawner.cpu_limit = 1
c.Spawner.mem_limit = '10G'
c.Spawner.cmd = ['jupyterhub-singleuser', '--allow-root']
c.JupyterHub.ssl_cert = '/srv/jupyterhub/xxx.crt'
c.JupyterHub.ssl_key = '/srv/jupyterhub/xxx.key'
c.Authenticator.admin_users = {'educationAdmin'}
c.JupyterHub.services = [
    {
        "name": "service-token",
        "admin": True,
        "api_token": "bb740514217440bda1d1c94881fa2dad",
    },
]
c.LocalAuthenticator.create_system_users = True
c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' https://xxx.com:7003 https://xxx.com http://localhost:8080"
    }
}
# c.Spawner.args = ['--NotebookApp.tornado_settings={'headers':{'Content-Security-Policy': 'frame-ancestors self https://xxx.com:7003 https://xxx.com http://localhost:8080',}}']
# c.JupyterHub.template_paths = ["/srv/jupyterhub/template"]
```
I don't know what else needs to be done, I just executed` docker-compose up` and this error occurred. Please help me, thanks！
