### ISSUE TITLE
Q: How to add additional network via docker-compose.yml?

### ISSUE THREAD

**Issue by Dmfama20** [jupyterhub/jupyterhub-deploy-docker#114]
Hi,
I tried to add an additional network via docker-compose.yml. So I added the lines 

 ```
 networks:
      - web
```
and 
```
networks:
  web:
    external: true
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
```
Unfortunately, this seems to override the standard docker-hub-network such that docker-hub is not able to connect to the db.
So, how is it possible to add an additional network?
(Background: I want to run docker-hub behind my reverse-proxy (traefik), which uses the network "web")
TIA!
Alex
