### ISSUE TITLE
Naming Conventions for Volumes - Docker Spawner

### ISSUE THREAD

**Issue by ajennings67** [jupyterhub/jupyterhub-deploy-docker#92]
Hi,

I have been customizing a deployment of this repo (https://github.com/defeo/jupyterhub-docker/) for internal use. 

One issue, I've been having relates to shared volumes in the spawned jupyterlab container. In the master branch of the repo I have been using to host my project, the name of the project was 'jupyterhub'. On the master, all of my shared volumes were working correctly. Subsequently, I created a branch named 'qmbase'. After making this change none of my shared volumes worked in jupyterlab.

With some tweaking, I was able to get my jupyterhub volumes to be mounted properly, but the spawned jupyterlab containers still have volumes mounted incorrectly.

Expected Behavior:
---
I was expecting the volume mounts to look something like:
`docker inspect jupyterhub_hub`

```
 "Mounts": [
            {
                "Type": "volume",
                "Name": "qmbase_fileserver_data",
                "Source": "/tad/docker/volumes/qmbase_fileserver_data/_data",
                "Destination": "/srv/fileserver",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "qmbase_jupyterhub_data",
                "Source": "/tad/docker/volumes/qmbase_jupyterhub_data/_data",
                "Destination": "/srv/jupyterhub",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "qmbase_jupyterlab_data",
                "Source": "/tad/docker/volumes/qmbase_jupyterlab_data/_data",
                "Destination": "/srv/jupyterlab",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
```

Actual Behavior:
---
As per `docker inspect jupyter-someUser`, the spawned jupyterlab user container is creating the following:

```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "jupyterhub-user-xbbl3nz",
                "Source": "/tad/docker/volumes/jupyterhub-user-xbbl3nz/_data",
                "Destination": "/home/qmacro",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "jupyterhub_jupyterlab_data",
                "Source": "/tad/docker/volumes/jupyterhub_jupyterlab_data/_data",
                "Destination": "/srv/jupyterlab",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "jupyterhub_fileserver_data",
                "Source": "/tad/docker/volumes/jupyterhub_fileserver_data/_data",
                "Destination": "/srv/fileserver",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
```
The spawner is actually creating these volumes from scratch:
![image](https://user-images.githubusercontent.com/25620161/65619506-448dbb00-df8e-11e9-94bc-dbfc088c07f6.png)

Additional Info
---
It seems like there is some default value that I am not changing to reflect the new project name, I just don't know where it is.

docker-compose.yml:
```
version: '3'

services:

    jupyterhub:
        build: jupyterhub
        container_name: jupyterhub_hub
        image: qmbase_jupyterhub
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jupyterhub_data:/srv/jupyterhub
            - jupyterlab_data:/srv/jupyterlab
            - fileserver_data:/srv/fileserver
        environment:
            DOCKER_JUPYTER_IMAGE: jupyterlab_img
            DOCKER_NETWORK_NAME: qmbase_network 
            KRB5_CONFIG: /etc/krb5.conf
            HUB_IP: jupyterhub_hub
            COMPOSE_PROJECT_NAME: qmbase
        labels:             
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:mcsfvldxtaas01.mcm.com"

    reverse-proxy:
        image: traefik
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "5000:5000"
        volumes:
            - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/pki/tls/private/server.crt:/etc/certs/server.crt
            - /etc/pki/tls/private/server.key:/etc/certs/server.key
    
    jupyterlab:
        build: jupyterlab
        image: jupyterlab_img
        container_name: jupyterlab-cont 
        command: echo
        volumes:
            - jupyterhub_data:/srv/jupyterhub
            - jupyterlab_data:/srv/jupyterlab
            - fileserver_data:/srv/fileserver

    fileserver:
        build: fileserver
        image: fileserver_img
        command: uwsgi --http-socket 0.0.0.0:5000 --wsgi-file app.py --callable app
        volumes: 
            - fileserver_data:/srv/fileserver
        labels:
            - "traefik.enable=true"
            - "traefik.backend=flask"
            - "traefik.frontend.rule=Host:mcsfvldxtaas01.mcm.com;PathPrefix:/files"

    clickhouse:         
        build: clickhouse              
        image: clickhouse_img         
        container_name: clickhouse-cont         
        volumes:             
            - clickhouse_data:/var/lib/clickhouse             
            - jupyterlab_data:/srv/jupyterlab         
        ports:             
            - "8123:8123"
            - "9000:9000" 
        
    drill:
        build: drill
        image: drill_img
        container_name: drill-cont
        volumes:
            - jupyterhub_data:/srv/jupyterhub
            - jupyterlab_data:/srv/jupyterlab
            - fileserver_data:/srv/fileserver
            - drill_data:/srv/drill
        ports:
            - "8047:8047"
            - "31010:31010"
        labels:             
            - "traefik.enable=true"                             
            - "traefik.frontend.rule=Host:mcsfvldxtaas01.mcm.com;PathPrefixStrip:/drill"
        tty: true
 
    luigi:
        build: luigi
        image: luigi_img
        container_name: luigi-cont
        volumes:
            - jupyterhub_data:/srv/jupyterhub
            - jupyterlab_data:/srv/jupyterlab
            - fileserver_data:/srv/fileserver
            - drill_data:/srv/drill
            - luigi_data:/srv/luigi
        ports:
            - "8082:8082"
        labels:             
            - "traefik.enable=true"                     
            - "traefik.frontend.rule=Host:mcsfvldxtaas01.mcm.com;PathPrefixStrip:/luigi"

        
volumes:
    jupyterhub_data:
    jupyterlab_data:
    fileserver_data:
    clickhouse_data:
    drill_data:
    luigi_data:

networks:
    default:
        external: 
            name: qmbase_network

```

jupyterhub_config.py:

```
import os
from subprocess import Popen, PIPE
from jupyterhub.auth import Authenticator
from tornado import gen

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.JupyterHub.hub_ip = os.environ['HUB_IP']
c.JupyterHub.debug_proxy = True
c.DockerSpawner.debug = True
c.DockerSpawner.image = os.environ['DOCKER_JUPYTER_IMAGE']
c.DockerSpawner.network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.extra_host_config = { 'network_mode': 'bridge' }
c.DockerSpawner.prefix = 'qmbase'
c.DockerSpawner.notebook_dir = '/home/qmacro'
c.DockerSpawner.volumes = { '{prefix}-user-{username}': '/home/qmacro', 
                            '{prefix}_jupyterlab_data': '/srv/jupyterlab',
                            '{prefix}fileserver': '/srv/fileserver',}




c.Spawner.default_url = '/lab'

c.JupyterHub.services = [
    {
        'name': 'cull_idle',
        'admin': True,
        'command': 'python /srv/jupyterhub/cull_idle_servers.py --timeout=360000'.split(),
    },
]

class KDBAuthenticator(Authenticator):

# deliberately ommitted 

c.JupyterHub.authenticator_class = KDBAuthenticator

```
